In [1]:
print("hello world!")

hello world!


In [8]:
a="aman"
print(f"my name  is {a}")

my name  is aman


In [3]:
import numpy as np
import time

In [11]:
a=[1,2,4,5,6,7,8,9,10]*10000

start=time .time()
for i in range(len(a)):
    a[i]=a[i]*2
print("\ntime taken by list:",time.time()-start)


time taken by list: 0.006825685501098633


In [12]:
a=[1,2,4,5,6,7,8,9,10]*10000
b=np.array(a)
start=time .time()
new_b=b*2
print("\ntime taken by numpy:",time.time()-start)


time taken by numpy: 0.0005533695220947266


In [2]:
import sys

In [12]:
a=[1,2,3,4,5]
arr=np.array(a)
print("list size:",sys.getsizeof(a))
print("array size:",arr.nbytes) 

list size: 104
array size: 40


In [15]:
arr=np.array([1,2,3,4,5])


In [13]:
arr=np.array(a)
arr.ndim

1

In [14]:
nb=np.array(a)
nb.ndim

1

In [15]:
p=np.array([[1,2,3],[4,5,6]])

In [17]:
p.ndim

2

In [23]:
l=[1,2,3,4,5,6,7,8,9,10]

In [24]:
for i in (1,2,3):
    l.append(i)

In [32]:
boom=np.arange(1,10,2)

In [33]:
print(boom)

[1 3 5 7 9]


In [37]:
a=np.linspace(0,1,10)

In [38]:
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [40]:
a=np.logspace(0,2,10)
print(a)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


In [47]:
a=np.zeros(1)
a

array([0.])

In [54]:
a=np.ones([2,3],dtype=int)
print(a)

[[1 1 1]
 [1 1 1]]


In [ ]:
arr = np.full([3,2],2) #rows,columns,defalt value
arr

array([[2, 2],
       [2, 2],
       [2, 2]])

In [17]:
abb = np.empty(7)
abb

array([-1.12769557e-311, -1.26761961e+202,  1.12771042e-311,
        1.12771042e-311,  1.48219694e-322,  1.97626258e-323,
        0.00000000e+000])

In [70]:
arr = np.random.rand(3,3)
arr

array([[0.63583633, 0.96628608, 0.24906548],
       [0.19054134, 0.20474259, 0.63692544],
       [0.07389243, 0.23765001, 0.91249314]])

In [2]:
def count_even(nums):
    count = 0
    for n in nums:
        if n % 2 == 0:
            count += 1
    return count

print(count_even([1, 2, 3, 4, 8]))


3


In [19]:
ran = np.random.rand(2,3)
ran

array([[0.31677144, 0.97494806, 0.1773676 ],
       [0.80458329, 0.07539255, 0.5461944 ]])

In [22]:
ran = np.random.randn(2,3)
ran

array([[ 0.39315281, -1.3562563 , -0.30144816],
       [-0.66577976, -1.03990957, -0.25182856]])

In [24]:
ran = np.random.randint(10,100)
ran

31

In [ ]:
ran = np.random.randint(10, 100,size = (2,3))
ran         

array([[55, 37, 59],
       [80, 22, 61]], dtype=int32)

In [ ]:
arr = np.array([1,2,3.1,4,5],dtype=int)
arr.dtype

dtype('int64')

In [37]:
arr.ndim        

1

In [ ]:
arr.shape   

(5,)

In [39]:
arr.size

5

In [40]:
arr.itemsize

8

In [37]:
arr= np.array([1,2,3,4,5,6])
reshape = arr.reshape(2,3)
print(reshape)

[[1 2 3]
 [4 5 6]]


In [38]:
bll = reshape.ravel()
bll

array([1, 2, 3, 4, 5, 6])

In [39]:
reshape[0] = 22
print(bll)
print(reshape)

[22 22 22  4  5  6]
[[22 22 22]
 [ 4  5  6]]


In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

In [10]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(b%a)
print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 1 0]
[1 4 9]


In [14]:
arr = np.array([1,4,9,16,25],dtype=int)
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


In [15]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [17]:
angles = np.array ([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [29]:
a = np.array([1,2,3,4,5])
print(a[0:2])         
print(a[-1:-4:-1])           

[1 2]
[5 4 3]


In [33]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix[0:2,:])
print(matrix[1:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[5 6]
 [8 9]]
